# ─────────────────────────────────────────────────────────────────────────────
# CyberGuard v2.0 — One-line installer for Windows (PowerShell)
#
# Run this in PowerShell (as Administrator for best results):
#
#   Set-ExecutionPolicy Bypass -Scope Process -Force
#   irm https://raw.githubusercontent.com/SpineSoloh/CyberGuard-V2.0/main/scripts/install.ps1 | iex
#
# What it does:
#   1. Checks for Python 3.9+  — opens python.org if missing
#   2. Creates a virtualenv in  %USERPROFILE%\.cyberguard\venv
#   3. pip-installs cyberguard  from GitHub
#   4. Adds a cyberguard.cmd    wrapper to %USERPROFILE%\.cyberguard\bin
#   5. Adds that folder to the  user PATH permanently
#   6. Prints a quick-start guide
# ─────────────────────────────────────────────────────────────────────────────
$ErrorActionPreference = "Stop"

$Repo       = "https://github.com/SpineSoloh/CyberGuard-V2.0"
$InstallDir = Join-Path $env:USERPROFILE ".cyberguard"
$VenvDir    = Join-Path $InstallDir "venv"
$BinDir     = Join-Path $InstallDir "bin"
$Version    = "2.0.0"
$MinMajor   = 3
$MinMinor   = 9

function Write-Banner {
    Write-Host ""
    Write-Host "  ╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
    Write-Host "  ║             CyberGuard v$Version Installer                     ║" -ForegroundColor Cyan
    Write-Host "  ║               Created by  Victoria TecHub                    ║" -ForegroundColor Cyan
    Write-Host "  ║       Forensic Triage Assistant                             ║" -ForegroundColor Cyan
    Write-Host "  ╚══════════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
    Write-Host ""
}

function Write-OK   ($msg) { Write-Host "[✓] $msg" -ForegroundColor Green  }
function Write-Warn ($msg) { Write-Host "[!] $msg" -ForegroundColor Yellow }
function Write-Fail ($msg) { Write-Host "[✗] $msg" -ForegroundColor Red    }
function Write-Step ($msg) { Write-Host "`n── $msg ──" -ForegroundColor Blue }

# ── Check admin ───────────────────────────────────────────────────────────────
Write-Banner

$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
    [Security.Principal.WindowsBuiltInRole]::Administrator
)
if (-not $isAdmin) {
    Write-Warn "Not running as Administrator — some CyberGuard v2.0 checks will be limited."
    Write-Warn "For full coverage, re-run PowerShell as Administrator."
}

# ── 1. Find Python ────────────────────────────────────────────────────────────
Write-Step "Checking Python"

function Find-Python {
    $candidates = @("python", "python3", "py")
    foreach ($cmd in $candidates) {
        try {
            $ver = & $cmd -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')" 2>$null
            if ($ver -match '(\d+)\.(\d+)') {
                $maj = [int]$Matches[1]; $min = [int]$Matches[2]
                if ($maj -ge $MinMajor -and $min -ge $MinMinor) { return $cmd }
            }
        } catch { continue }
    }
    return $null
}

$Python = Find-Python

if (-not $Python) {
    Write-Fail "Python $MinMajor.$MinMinor+ not found."
    Write-Warn "Download Python from: https://python.org/downloads/windows/"
    Write-Warn "Make sure to check 'Add Python to PATH' during installation."
    $open = Read-Host "Open python.org in your browser now? [Y/n]"
    if ($open -ne 'n' -and $open -ne 'N') {
        Start-Process "https://python.org/downloads/windows/"
    }
    Write-Host "Re-run this installer after Python is installed." -ForegroundColor Yellow
    exit 1
}

$pyVer = & $Python --version
Write-OK "Found: $Python  ($pyVer)"

# ── 2. Create virtualenv ──────────────────────────────────────────────────────
Write-Step "Setting up virtual environment"

New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
New-Item -ItemType Directory -Force -Path $BinDir     | Out-Null

if (Test-Path $VenvDir) {
    Write-Warn "Existing venv found — upgrading"
    & $Python -m venv $VenvDir --upgrade
} else {
    & $Python -m venv $VenvDir
    Write-OK "Created venv at $VenvDir"
}

$VenvPy  = Join-Path $VenvDir "Scripts\python.exe"
$VenvPip = Join-Path $VenvDir "Scripts\pip.exe"

& $VenvPip install --upgrade pip --quiet

# ── 3. Install cyberguard ─────────────────────────────────────────────────────
Write-Step "Installing CyberGuard v2.0"

& $VenvPip install "git+$Repo.git@main" --quiet
Write-OK "CyberGuard v$Version installed"

# ── 4. Write wrapper .cmd ─────────────────────────────────────────────────────
Write-Step "Installing CyberGuard CLI command"

$WrapperPath = Join-Path $BinDir "cyberguard.cmd"
$WrapperContent = @"
@echo off
REM Cyberguard wrapper — auto-generated by install.ps1
"$VenvPy" -m cyberguard %*
"@
Set-Content -Path $WrapperPath -Value $WrapperContent -Encoding ASCII
Write-OK "Wrapper written to $WrapperPath"

# ── 5. Add to PATH ────────────────────────────────────────────────────────────
Write-Step "Updating PATH"

$UserPath = [Environment]::GetEnvironmentVariable("PATH", "User")
if ($UserPath -notlike "*$BinDir*") {
    [Environment]::SetEnvironmentVariable("PATH", "$BinDir;$UserPath", "User")
    Write-OK "Added $BinDir to user PATH"
    Write-Warn "Restart your terminal for 'cyberguard' to be available system-wide."
} else {
    Write-OK "PATH already contains $BinDir"
}

# Update current session PATH too
$env:PATH = "$BinDir;$env:PATH"

# ── 6. Done ───────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  ╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "  ║  Installation complete!                                      ║" -ForegroundColor Green
Write-Host "  ╚══════════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""
Write-Host "  Quick start (in a new terminal):"
Write-Host ""
Write-Host "    cyberguard                        # basic scan"
Write-Host "    cyberguard --teaching             # scan with explanations"
Write-Host "    cyberguard --browser --shell      # include history (consent prompt)"
Write-Host "    cyberguard --vt-key YOUR_KEY      # VirusTotal hash checking"
Write-Host "    cyberguard --help                 # all options"
Write-Host ""
Write-Host "  For a full privileged scan, run PowerShell as Administrator:"
Write-Host "    cyberguard --require-admin --teaching"
Write-Host ""
Write-Host "  To uninstall CyberGuard v2.0:"
Write-Host "    Remove-Item -Recurse -Force $InstallDir"
Write-Host ""
