#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# CyberGuard v2.0 — One-line installer for Linux & macOS
#
# Usage (copy-paste into your terminal):
#   curl -fsSL https://raw.githubusercontent.com/YOUR_USERNAME/cyberguard/main/scripts/install.sh | bash
#
# What it does:
#   1. Checks for Python 3.9+   — offers to install via OS package manager if missing
#   2. Creates a virtualenv in  ~/.cyberguard/venv   (no system-python pollution)
#   3. pip-installs cyberguard  from the GitHub release
#   4. Writes a thin wrapper    /usr/local/bin/cyberguard  (or ~/bin if no sudo)
#   5. Prints a quick-start guide
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

REPO="https://github.com/YOUR_USERNAME/cyberguard"
INSTALL_DIR="${HOME}/.cyberguard"
VENV_DIR="${INSTALL_DIR}/venv"
MIN_PY_MAJOR=3
MIN_PY_MINOR=9
VERSION="2.0.0"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'

banner() {
  echo -e "${BLUE}"
  echo "  ╔══════════════════════════════════════════════════════════════╗"
  echo "  ║             CyberGuard v${VERSION} Installer                     ║"
  echo "  ║               Created by  Victoria TecHub                    ║"
  echo "  ║       Forensic Triage Assistant                             ║"
  echo "  ╚══════════════════════════════════════════════════════════════╝"
  echo -e "${NC}"
}

info()    { echo -e "${GREEN}[✓]${NC} $*"; }
warn()    { echo -e "${YELLOW}[!]${NC} $*"; }
error()   { echo -e "${RED}[✗]${NC} $*" >&2; }
section() { echo -e "\n${BLUE}── $* ──${NC}"; }

# ── 1. Python check ───────────────────────────────────────────────────────────
banner
section "Checking Python"

find_python() {
  for cmd in python3 python python3.12 python3.11 python3.10 python3.9; do
    if command -v "$cmd" &>/dev/null; then
      ver=$("$cmd" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')" 2>/dev/null)
      major=$(echo "$ver" | cut -d. -f1)
      minor=$(echo "$ver" | cut -d. -f2)
      if [ "$major" -ge "$MIN_PY_MAJOR" ] && [ "$minor" -ge "$MIN_PY_MINOR" ]; then
        echo "$cmd"
        return 0
      fi
    fi
  done
  return 1
}

PYTHON=$(find_python || true)

if [ -z "$PYTHON" ]; then
  error "Python ${MIN_PY_MAJOR}.${MIN_PY_MINOR}+ not found."
  OS="$(uname -s)"
  if [ "$OS" = "Darwin" ]; then
    warn "Install Python with Homebrew:  brew install python"
    warn "Or download from:              https://python.org/downloads"
  elif [ -f /etc/debian_version ]; then
    warn "Install with:  sudo apt install python3 python3-venv python3-pip"
  elif [ -f /etc/redhat-release ]; then
    warn "Install with:  sudo dnf install python3 python3-pip"
  fi
  echo ""
  read -rp "Install Python now and re-run this script? (press Enter to exit) "
  exit 1
fi

info "Found: $PYTHON ($("$PYTHON" --version))"

# ── 2. Create virtualenv ──────────────────────────────────────────────────────
section "Setting up virtual environment"

mkdir -p "$INSTALL_DIR"

if [ -d "$VENV_DIR" ]; then
  warn "Existing venv found at $VENV_DIR — upgrading in place"
  "$PYTHON" -m venv "$VENV_DIR" --upgrade
else
  "$PYTHON" -m venv "$VENV_DIR"
  info "Created venv at $VENV_DIR"
fi

PY="${VENV_DIR}/bin/python"
PIP="${VENV_DIR}/bin/pip"

"$PIP" install --upgrade pip --quiet

# ── 3. Install cyberguard ─────────────────────────────────────────────────────
section "Installing Cyberguard"

"$PIP" install "git+${REPO}.git@main" --quiet
info "CyberGuard v${VERSION} installed"

# ── 4. Write wrapper script ───────────────────────────────────────────────────
section "Installing CLI command"

WRAPPER_CONTENT="#!/usr/bin/env bash
# Cyberguard wrapper — auto-generated by install.sh
exec \"${PY}\" -m cyberguard \"\$@\"
"

# Try /usr/local/bin first (needs sudo), fall back to ~/bin
if [ -w /usr/local/bin ]; then
  WRAPPER=/usr/local/bin/cyberguard
  echo "$WRAPPER_CONTENT" > "$WRAPPER"
  chmod +x "$WRAPPER"
  info "Installed system-wide:  $WRAPPER"
else
  mkdir -p "${HOME}/bin"
  WRAPPER="${HOME}/bin/cyberguard"
  echo "$WRAPPER_CONTENT" > "$WRAPPER"
  chmod +x "$WRAPPER"
  info "Installed to:  $WRAPPER"
  # Check if ~/bin is on PATH
  if [[ ":$PATH:" != *":${HOME}/bin:"* ]]; then
    warn "Add ~/bin to your PATH by adding this to ~/.bashrc or ~/.zshrc:"
    echo "    export PATH=\"\$HOME/bin:\$PATH\""
  fi
fi

# ── 5. Done ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  Installation complete!                                      ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo "  Quick start:"
echo ""
echo "    cyberguard                        # basic scan (CyberGuard v2.0)"
echo "    cyberguard --teaching             # scan with explanations"
echo "    sudo cyberguard --require-admin   # full privileged scan"
echo "    cyberguard --browser --shell      # include history (prompts consent)"
echo "    cyberguard --vt-key YOUR_KEY      # VirusTotal hash checking"
echo "    cyberguard --help                 # all options"
echo ""
echo "  To uninstall CyberGuard v2.0:"
echo "    rm -rf ~/.cyberguard && rm -f ${WRAPPER}"
echo ""
